name: Python Lint & Test

on: [push]

jobs:
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Lint code with Ruff
        run: ruff check python --output-format=github --target-version=py310

      - name: Check code formatting with Ruff
        run: ruff format python --diff --target-version=py310
        continue-on-error: true

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest python --doctest-modules --junitxml=junit/test-results.xml --cov=python --cov-report=xml --cov-report=html
